### Read existing shared resources (read-only, nothing is created or modified) ###

# The default VPC in this region -- the shared RDS (sdx-ticket-database-1) lives in it.
data "aws_vpc" "default" {
  default = true
}

# The default VPC's per-AZ "default subnets" -- all public (auto-assign public IP).
data "aws_subnets" "default_public" {
  filter {
    name   = "vpc-id"
    values = [data.aws_vpc.default.id]
  }
  filter {
    name   = "default-for-az"
    values = ["true"]
  }
}

# Existing shared RDS instance, read-only (endpoint/port). Never managed or modified by this terraform.
data "aws_db_instance" "sow_rds" {
  db_instance_identifier = var.rds_db_instance_identifier
}

# Latest Amazon Linux 2023 AMI, so we don't hardcode an AMI ID that goes stale.
# arm64 because var.instance_type defaults to t4g.micro (Graviton); switch to *-x86_64 if
# instance_type is changed back to a t3/t2/m5-family (Intel/AMD) type.
data "aws_ami" "al2023" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["al2023-ami-2023.*-arm64"]
  }
  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

# Used to auto-detect the public IP of whoever is running `terraform apply`, as the default SSH allowlist.
data "http" "my_ip" {
  url = "https://checkip.amazonaws.com"
}

locals {
  ssh_cidr = var.allowed_ssh_cidr != null ? var.allowed_ssh_cidr : "${chomp(data.http.my_ip.response_body)}/32"
}

### New EC2 key pair (generated by terraform, private key stays local, never uploaded anywhere) ###

resource "tls_private_key" "app" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "app" {
  key_name   = var.key_pair_name
  public_key = tls_private_key.app.public_key_openssh
}

resource "local_sensitive_file" "private_key" {
  content         = tls_private_key.app.private_key_pem
  filename        = "${path.module}/${var.key_pair_name}.pem"
  file_permission = "0600"
}

### Dedicated EC2 security group (brand new, fully owned by terraform, destroy removes it entirely) ###

resource "aws_security_group" "app" {
  name_prefix = "${var.name_prefix}-"
  description = "SOW automation app EC2 - SSH + app port"
  vpc_id      = data.aws_vpc.default.id

  # SSH, restricted to allowed_ssh_cidr (defaults to the apply-time caller's IP, see locals.ssh_cidr)
  ingress {
    description = "SSH from allowed_ssh_cidr"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = [local.ssh_cidr]
  }

  # uvicorn served directly, no nginx/ALB in front
  ingress {
    description = "App (uvicorn) direct access"
    from_port   = var.app_port
    to_port     = var.app_port
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  # Outbound: needs RDS (5432), dnf/pip package installs, and future Bedrock calls
  egress {
    description = "Allow all outbound"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name = "${var.name_prefix}-sg"
  }

  lifecycle {
    create_before_destroy = true
  }
}

# Add one rule to an existing SG ("local") on the shared RDS, allowing only this new SG into port 5432.
# Uses a standalone rule resource instead of importing the whole aws_security_group into state, so
# `terraform destroy` only removes this one rule -- it never touches the RDS or any other system's rules.
resource "aws_vpc_security_group_ingress_rule" "rds_from_app" {
  security_group_id            = var.rds_ingress_security_group_id
  referenced_security_group_id = aws_security_group.app.id
  from_port                    = data.aws_db_instance.sow_rds.port
  to_port                      = data.aws_db_instance.sow_rds.port
  ip_protocol                  = "tcp"
  description                  = "sow-automation-upload EC2 app to RDS (managed by infra/terraform, safe to destroy independently)"
}

### The EC2 instance itself ###################################################

resource "aws_instance" "app" {
  ami                    = data.aws_ami.al2023.id
  instance_type          = var.instance_type
  subnet_id              = element(data.aws_subnets.default_public.ids, 0)
  vpc_security_group_ids = [aws_security_group.app.id]
  key_name               = aws_key_pair.app.key_name

  associate_public_ip_address = true

  root_block_device {
    volume_type = "gp3"
    volume_size = var.root_volume_size_gb
  }

  user_data = templatefile("${path.module}/user_data.sh.tpl", {
    app_port = var.app_port
  })
  # Re-run provisioning if user_data changes (e.g. app_port changes the systemd unit)
  user_data_replace_on_change = true

  tags = {
    Name = var.name_prefix
  }
}

resource "aws_eip" "app" {
  instance = aws_instance.app.id
  domain   = "vpc"

  tags = {
    Name = "${var.name_prefix}-eip"
  }
}
