// Mock 資料：篩選代碼標籤字典（雙語）＋ 16 筆案例資料
// 每筆案例的 detail = { A, B, C }，前端依角色累加規則（見 app.js ROLE_SECTIONS）決定顯示哪些區塊，
// 而不是替每個角色各寫一份窄化內容 —— 這是修正參考圖 ui_v1.png 中「PM 只顯示 B、SA 只顯示 C」錯誤的核心。

const LABELS = {
  service: {
    ai_genai: { zh: 'AI / GenAI', en: 'AI / GenAI', color: 'purple' },
    automation: { zh: '自動化', en: 'Automation', color: 'purple' },
    data_analytics: { zh: '數據分析', en: 'Data Analytics', color: 'purple' },
    security: { zh: '資安防護', en: 'Security', color: 'purple' },
  },
  usecase: {
    doc_processing: { zh: '文件處理', en: 'Document Processing', color: 'amber' },
    nlp: { zh: 'NLP', en: 'NLP', color: 'amber' },
    ocr: { zh: 'OCR', en: 'OCR', color: 'amber' },
    data_insight: { zh: '數據分析', en: 'Data Analysis', color: 'amber' },
    fraud_detect: { zh: '稽核偵測', en: 'Anomaly Detection', color: 'amber' },
    demand_forecast: { zh: '需求預測', en: 'Demand Forecasting', color: 'amber' },
    conversation: { zh: '客服對話', en: 'Conversational AI', color: 'amber' },
    equipment_monitor: { zh: '設備監控', en: 'Equipment Monitoring', color: 'amber' },
    route_optimize: { zh: '路線優化', en: 'Route Optimization', color: 'amber' },
  },
  skill: {
    aws: { zh: 'AWS', en: 'AWS', color: 'blue' },
    claude: { zh: 'Claude', en: 'Claude', color: 'orange' },
    n8n: { zh: 'n8n', en: 'n8n', color: 'teal' },
    python: { zh: 'Python', en: 'Python', color: 'indigo' },
    bedrock: { zh: 'Bedrock', en: 'Bedrock', color: 'orange' },
    restapi: { zh: 'RESTful API', en: 'RESTful API', color: 'gray' },
  },
  role: {
    PM: { zh: 'PM', en: 'PM' },
    RD: { zh: 'RD', en: 'RD' },
    QC: { zh: 'QC', en: 'QC' },
    SA: { zh: 'SA', en: 'SA' },
    UIUX: { zh: 'UI/UX', en: 'UI/UX' },
  },
  wbsPhase: {
    kickoff: { zh: '專案啟動', en: 'Kickoff' },
    analysis: { zh: '需求訪談', en: 'Requirement Analysis' },
    design_dev: { zh: '設計與開發', en: 'Design & Development' },
    testing: { zh: '測試與修復', en: 'Testing & Fixes' },
    uat: { zh: '驗收上線', en: 'UAT & Go-live' },
    handover: { zh: '結案交付', en: 'Handover' },
  },
  deliverable: {
    workflow_template: { zh: 'n8n workflow 樣板', en: 'n8n workflow template' },
    user_manual: { zh: '使用者操作手冊', en: 'User operation manual' },
    uat_report: { zh: '驗收測試報告', en: 'UAT report' },
    source_repo: { zh: '原始碼交接', en: 'Source code handover' },
    training_session: { zh: '教育訓練場次', en: 'Training session' },
    ops_manual: { zh: '維運手冊', en: 'Operations manual' },
  },
  archNode: {
    user: { zh: '使用者', en: 'User' },
    ai_portal: { zh: 'AI Agent Portal', en: 'AI Agent Portal' },
    n8n_workflow: { zh: 'n8n Workflow', en: 'n8n Workflow' },
    claude_bedrock: { zh: 'Claude 3 (Bedrock)', en: 'Claude 3 (Bedrock)' },
    external_sources: { zh: '外部資料來源', en: 'External Data Sources' },
  },
  archNodeDetail: {
    user: { zh: ['申請文件上傳', '檢核結果查詢', '報告下載/追蹤'], en: ['Upload application docs', 'Query review results', 'Download / track reports'] },
    ai_portal: { zh: ['文件結構解析', '欄位比對邏輯'], en: ['Document structure parsing', 'Field matching logic'] },
    n8n_workflow: { zh: ['流程 orchestration', '任務調度', '資料轉換'], en: ['Process orchestration', 'Task scheduling', 'Data transformation'] },
    claude_bedrock: { zh: ['資訊萃取', '資料比對', '檢核結果評分', '摘要生成'], en: ['Information extraction', 'Data matching', 'Review scoring', 'Summary generation'] },
    external_sources: { zh: ['基金資料庫', '投信投顧公會', '風險名單', '基金公司網站'], en: ['Fund database', 'SITCA registry', 'Risk watchlist', 'Fund company site'] },
  },
  techstack: {
    aws_ec2: 'AWS EC2',
    bedrock_claude3: 'Amazon Bedrock (Claude 3)',
    n8n_self_hosting: 'n8n Self Hosting',
    nlp: 'NLP',
    python: 'Python',
    restful_api: 'RESTful API',
    aws_lambda: 'AWS Lambda',
    aws_s3: 'Amazon S3',
    textract: 'Amazon Textract',
    sagemaker: 'Amazon SageMaker',
    aws_rds: 'Amazon RDS',
    quicksight: 'Amazon QuickSight',
  },
  corefunction: {
    form_extraction: { zh: '申請表資訊萃取', en: 'Application form extraction' },
    data_matching: { zh: '資料自動比對', en: 'Automated data matching' },
    risk_scoring: { zh: '檢核結果評分', en: 'Review scoring' },
    report_gen: { zh: '報告生成', en: 'Report generation' },
    notification: { zh: '通知與提醒', en: 'Notification & alerts' },
    dashboard: { zh: '儀表板視覺化', en: 'Dashboard visualization' },
    anomaly_alert: { zh: '異常即時警示', en: 'Real-time anomaly alerts' },
  },
  status: {
    planning: { zh: '規劃中', en: 'Planning' },
    in_progress: { zh: '執行中', en: 'In Progress' },
    completed: { zh: '已結案', en: 'Completed' },
  },
};

function L(dict, code, lang) {
  return LABELS[dict][code] ? LABELS[dict][code][lang] : code;
}

const CASES = [
  {
    id: 1,
    industry: 'Financial Services',
    icon: '👤',
    title: { zh: 'AI 基金商品檢核系統', en: 'AI Fund Product Compliance Checker' },
    description: {
      zh: '透過 AI 自動擷取申請表資訊，自動比對外部資料並生成檢核報告，檢核時間降低 50%，提升準確性與合規性。',
      en: 'Automatically extracts application data with AI, cross-checks external sources, and generates review reports — cutting review time by 50%.',
    },
    serviceCategory: 'ai_genai',
    useCase: 'doc_processing',
    skills: ['aws', 'claude', 'n8n'],
    date: '2025-11-03',
    creator: 'Christine Wang',
    detail: {
      A: {
        industryBackground: { zh: '該客戶為國內大型基金代銷機構，旗下涵蓋多家投信合作的基金商品，每月須受理大量申購與轉換申請，長期面對主管機關對申購文件檢核與法遵留存的高標準要求。', en: 'A major domestic fund distributor offering products from multiple asset managers, handling a high volume of monthly subscription and switch requests, and facing strict regulator demands for application review and compliance record-keeping.' },
        challenge: { zh: '該機構每月需人工檢核逾百件基金申購文件，逐筆比對申請表、風險評估問卷與外部名單，平均每件耗時 4 小時，人力負擔重且容易因疲勞產生疏漏，一旦檢核疏漏可能觸及法遵風險。', en: 'Staff manually review over a hundred fund subscription files each month, cross-checking application forms, risk-assessment questionnaires, and external watchlists line by line at roughly 4 hours per file — a heavy workload prone to fatigue-driven oversights that can expose the firm to compliance risk.' },
        solution: { zh: '透過 AI 自動擷取申請表關鍵資訊，即時比對外部資料庫與風險名單，並自動生成標準化檢核報告，讓審核人員只需複核系統標記的異常項目即可完成把關。', en: 'AI automatically extracts key data from application forms, cross-checks it against external databases and risk watchlists in real time, and generates a standardized review report — so staff only need to verify the items the system flags as anomalies.' },
        kpis: [
          { icon: '⏱️', value: '50%', label: { zh: '檢核時間縮短', en: 'Faster review time' } },
          { icon: '🕑', value: '20hr', label: { zh: '每月省人力', en: 'Labor hours saved / mo' } },
          { icon: '💰', value: 'NT$240K', label: { zh: '年節省成本', en: 'Cost saved / yr' } },
          { icon: '✅', value: 'Audit Trail', label: { zh: '建立稽核軌跡，符合監理要求', en: 'Established, meets regulatory needs' } },
        ],
      },
      B: {
        owner: 'Christine Wang', teamSize: 6, period: '2026/01/05 - 2026/03/13', status: 'planning',
        team: [{ role: 'PM', count: 1 }, { role: 'RD', count: 2 }, { role: 'QC', count: 1 }, { role: 'SA', count: 1 }, { role: 'UIUX', count: 1 }],
        wbs: [
          { phase: 'kickoff', weeks: 1, date: '1/5 - 1/9' },
          { phase: 'analysis', weeks: 1, date: '1/12 - 1/16' },
          { phase: 'design_dev', weeks: 3, date: '1/19 - 2/6' },
          { phase: 'testing', weeks: 2, date: '2/9 - 2/20' },
          { phase: 'uat', weeks: 1, date: '3/2 - 3/6', ongoing: true },
        ],
        cost: { total: 'NT$ 1,920,000', manDays: 48 },
        deliverables: ['workflow_template', 'user_manual', 'uat_report'],
      },
      C: {
        architecture: ['user', 'ai_portal', 'n8n_workflow', 'claude_bedrock', 'external_sources'],
        techStack: ['aws_ec2', 'bedrock_claude3', 'n8n_self_hosting', 'nlp', 'python', 'restful_api'],
        coreFunctions: ['form_extraction', 'data_matching', 'risk_scoring', 'report_gen', 'notification'],
      },
    },
  },
  {
    id: 2,
    industry: 'Financial Services',
    icon: '🤝',
    title: { zh: '信貸文件智慧審查系統', en: 'Smart Loan Document Review System' },
    description: { zh: '自動辨識與審查信貸文件，降低人工審查時間。', en: 'Automatically identifies and reviews loan documents to reduce manual review time.' },
    serviceCategory: 'ai_genai', useCase: 'doc_processing', skills: ['aws'], date: '2025-10-31', creator: 'Ken Lin',
    detail: {
      A: {
        industryBackground: { zh: '該客戶為區域銀行消金部門，每月受理大量個人信貸與小額貸款申請，分行與線上管道並行送件，業務量隨促案活動大幅波動。', en: "A regional bank's consumer-lending division that processes high volumes of personal and small-ticket loan applications each month across both branch and online channels, with volume fluctuating sharply during promotional campaigns." },
        challenge: { zh: '信貸文件種類繁多，收入證明、財力文件與信用報告格式不一，審查人員需逐案人工判讀並比對授信規則，耗時且容易因人為判斷差異造成審查標準不一致。', en: 'Loan documents vary widely in format — income proof, asset statements, credit reports — forcing reviewers to manually interpret each case against lending rules, which is slow and prone to inconsistent standards across different reviewers.' },
        solution: { zh: 'AI 自動辨識文件類型並擷取關鍵欄位，套用對應的授信審查規則進行初篩，並標記需要人工複核的高風險案件，加速核貸流程並提升審查一致性。', en: 'AI automatically classifies each document type, extracts key fields, and applies the matching lending rules for an initial screen, flagging only high-risk cases for manual review — speeding up approvals and improving review consistency.' },
        kpis: [
          { icon: '⏱️', value: '45%', label: { zh: '審查時間縮短', en: 'Faster review time' } },
          { icon: '🕑', value: '15hr', label: { zh: '每月省人力', en: 'Labor hours saved / mo' } },
          { icon: '💰', value: 'NT$180K', label: { zh: '年節省成本', en: 'Cost saved / yr' } },
          { icon: '✅', value: '99%', label: { zh: '審查一致性', en: 'Review consistency' } },
        ],
      },
      B: {
        owner: 'Ken Lin', teamSize: 5, period: '2026/02/02 - 2026/03/27', status: 'planning',
        team: [{ role: 'PM', count: 1 }, { role: 'RD', count: 2 }, { role: 'QC', count: 1 }, { role: 'SA', count: 1 }],
        wbs: [
          { phase: 'kickoff', weeks: 1, date: '2/2 - 2/6' },
          { phase: 'analysis', weeks: 1, date: '2/9 - 2/13' },
          { phase: 'design_dev', weeks: 3, date: '2/16 - 3/6' },
          { phase: 'testing', weeks: 2, date: '3/9 - 3/20' },
          { phase: 'uat', weeks: 1, date: '3/23 - 3/27', ongoing: true },
        ],
        cost: { total: 'NT$ 1,540,000', manDays: 39 },
        deliverables: ['user_manual', 'uat_report', 'ops_manual'],
      },
      C: {
        architecture: ['user', 'ai_portal', 'n8n_workflow', 'claude_bedrock', 'external_sources'],
        techStack: ['aws_ec2', 'textract', 'python', 'restful_api'],
        coreFunctions: ['form_extraction', 'data_matching', 'report_gen'],
      },
    },
  },
  {
    id: 3,
    industry: 'Financial Services',
    icon: '🏛️',
    title: { zh: '智能合約風險審查平台', en: 'Smart Contract Risk Review Platform' },
    description: { zh: '利用 NLP 與規則引擎，自動檢測合約的風險與缺漏。', en: 'Uses NLP and rule engines to automatically detect contract risks and gaps.' },
    serviceCategory: 'ai_genai', useCase: 'nlp', skills: ['aws'], date: '2025-10-28', creator: 'Amy Su',
    detail: {
      A: {
        industryBackground: { zh: '該客戶為金融控股公司法務室，每年須審閱數百份與供應商、合作夥伴及客戶往來的合約，合約類型與條款複雜度都在持續增加。', en: "A financial holding company's legal office reviewing hundreds of vendor, partner, and customer contracts each year, with contract types and clause complexity both steadily increasing." },
        challenge: { zh: '合約條款繁雜，法務人員必須逐條檢視違約金、責任限制與資料保護等高風險條款，人工審閱耗時且容易在龐大文字量中遺漏關鍵風險，延誤合約簽署時程。', en: 'Contract clauses are complex — legal staff must review liquidated-damages, liability-limitation, and data-protection clauses line by line, which is slow and risks missing critical exposure buried in dense text, delaying contract sign-off.' },
        solution: { zh: 'NLP 模型自動掃描合約全文，標記高風險條款並提出修改建議，讓法務人員能優先處理系統標示的重點段落，加快審閱速度並降低風險遺漏。', en: 'An NLP model scans the full contract text, flags high-risk clauses, and suggests revisions — letting legal staff focus first on system-highlighted passages, speeding up review and reducing the chance of missed risk.' },
        kpis: [
          { icon: '⏱️', value: '60%', label: { zh: '審閱時間縮短', en: 'Faster review time' } },
          { icon: '🕑', value: '25hr', label: { zh: '每月省人力', en: 'Labor hours saved / mo' } },
          { icon: '💰', value: 'NT$300K', label: { zh: '年節省成本', en: 'Cost saved / yr' } },
          { icon: '✅', value: '風險前置', label: { zh: '揭露', en: 'Early risk disclosure' } },
        ],
      },
      B: {
        owner: 'Amy Su', teamSize: 5, period: '2026/01/12 - 2026/03/06', status: 'planning',
        team: [{ role: 'PM', count: 1 }, { role: 'RD', count: 2 }, { role: 'SA', count: 1 }, { role: 'QC', count: 1 }],
        wbs: [
          { phase: 'kickoff', weeks: 1, date: '1/12 - 1/16' },
          { phase: 'analysis', weeks: 2, date: '1/19 - 1/30' },
          { phase: 'design_dev', weeks: 3, date: '2/2 - 2/20' },
          { phase: 'testing', weeks: 1, date: '2/23 - 2/27' },
          { phase: 'uat', weeks: 1, date: '3/2 - 3/6', ongoing: true },
        ],
        cost: { total: 'NT$ 1,680,000', manDays: 42 },
        deliverables: ['user_manual', 'uat_report'],
      },
      C: {
        architecture: ['user', 'ai_portal', 'n8n_workflow', 'claude_bedrock', 'external_sources'],
        techStack: ['aws_ec2', 'nlp', 'python', 'sagemaker'],
        coreFunctions: ['data_matching', 'risk_scoring', 'report_gen'],
      },
    },
  },
  {
    id: 4,
    industry: 'Financial Services',
    icon: '🛡️',
    title: { zh: '客戶 KYC 文件自動驗證', en: 'Customer KYC Document Auto-verification' },
    description: { zh: '自動驗證客戶身分與文件真實性，加速開戶流程。', en: 'Automatically verifies customer identity and document authenticity to speed up onboarding.' },
    serviceCategory: 'automation', useCase: 'ocr', skills: ['aws'], date: '2025-10-28', creator: 'Derek Wu',
    detail: {
      A: {
        industryBackground: { zh: '該客戶為數位銀行，主打線上快速開戶，每月新戶申請量大，且因無實體分行需高度仰賴線上身分驗證機制來符合洗錢防制與防偽要求。', en: 'A digital bank positioned around fast online onboarding, processing a high volume of new account applications each month, and — having no physical branches — relying heavily on online identity verification to meet AML and anti-fraud requirements.' },
        challenge: { zh: '開戶審核需人工核對身分證件、自拍比對與地址證明等多項資料，流程冗長，尖峰時段容易造成審核延遲，且人工比對防偽細節時容易產生疏漏。', en: 'Onboarding review requires manually cross-checking ID documents, selfie matching, and proof of address; the process is lengthy, causing delays during peak periods, and manual anti-fraud checks are prone to missed details.' },
        solution: { zh: 'OCR 自動辨識證件內容並與外部資料庫比對真偽，結合人臉辨識確認申請人身分，即時完成身分驗證並自動標記可疑案件供人工複核。', en: 'OCR automatically reads ID documents and cross-checks authenticity against external databases, combined with facial recognition to confirm applicant identity — completing verification instantly and flagging only suspicious cases for manual review.' },
        kpis: [
          { icon: '⏱️', value: '70%', label: { zh: '開戶時間縮短', en: 'Faster onboarding' } },
          { icon: '🕑', value: '18hr', label: { zh: '每月省人力', en: 'Labor hours saved / mo' } },
          { icon: '💰', value: 'NT$210K', label: { zh: '年節省成本', en: 'Cost saved / yr' } },
          { icon: '✅', value: '防偽比對', label: { zh: '降低偽造風險', en: 'Reduced forgery risk' } },
        ],
      },
      B: {
        owner: 'Derek Wu', teamSize: 6, period: '2026/01/19 - 2026/03/20', status: 'planning',
        team: [{ role: 'PM', count: 1 }, { role: 'RD', count: 2 }, { role: 'QC', count: 1 }, { role: 'SA', count: 1 }, { role: 'UIUX', count: 1 }],
        wbs: [
          { phase: 'kickoff', weeks: 1, date: '1/19 - 1/23' },
          { phase: 'analysis', weeks: 1, date: '1/26 - 1/30' },
          { phase: 'design_dev', weeks: 4, date: '2/2 - 2/27' },
          { phase: 'testing', weeks: 1, date: '3/2 - 3/6' },
          { phase: 'uat', weeks: 2, date: '3/9 - 3/20', ongoing: true },
        ],
        cost: { total: 'NT$ 1,860,000', manDays: 47 },
        deliverables: ['user_manual', 'training_session', 'uat_report'],
      },
      C: {
        architecture: ['user', 'ai_portal', 'n8n_workflow', 'claude_bedrock', 'external_sources'],
        techStack: ['aws_ec2', 'textract', 'aws_s3', 'restful_api'],
        coreFunctions: ['form_extraction', 'data_matching', 'notification'],
      },
    },
  },
  {
    id: 5,
    industry: 'Financial Services',
    icon: '📄',
    title: { zh: '保險理賠文件自動化處理', en: 'Insurance Claims Document Automation' },
    description: { zh: 'AI 擷取理賠文件並比對保單資料，縮短理賠時間。', en: 'AI extracts claims documents and cross-checks policy data to shorten claims processing.' },
    serviceCategory: 'ai_genai', useCase: 'doc_processing', skills: ['aws'], date: '2025-10-22', creator: 'Grace Chen',
    detail: {
      A: {
        industryBackground: { zh: '該客戶為大型保險公司理賠部門，每月受理大量意外、醫療與財產理賠申請，理賠速度與服務品質直接影響保戶續保意願與口碑。', en: "A large insurer's claims department handling a high volume of accident, medical, and property claims each month, where claim speed and service quality directly affect policyholder retention and word-of-mouth." },
        challenge: { zh: '理賠文件包含診斷書、收據與事故證明等多種格式，理賠人員需人工比對保單條款逐項核算給付金額，耗時且容易因人工計算誤差影響理賠準確性。', en: 'Claims documents span diagnoses, receipts, and incident reports in varied formats; adjusters must manually cross-reference policy terms to calculate payouts line by line, which is slow and prone to calculation errors that affect payout accuracy.' },
        solution: { zh: 'AI 自動擷取理賠文件中的關鍵資訊，比對保單條款與給付規則，自動產出理賠試算結果，理賠人員只需覆核系統試算即可完成結案。', en: "AI automatically extracts key data from claims documents, matches it against policy terms and payout rules, and generates a payout calculation automatically — adjusters simply verify the system's result to close the case." },
        kpis: [
          { icon: '⏱️', value: '55%', label: { zh: '理賠時間縮短', en: 'Faster claims processing' } },
          { icon: '🕑', value: '22hr', label: { zh: '每月省人力', en: 'Labor hours saved / mo' } },
          { icon: '💰', value: 'NT$260K', label: { zh: '年節省成本', en: 'Cost saved / yr' } },
          { icon: '✅', value: '滿意度提升', label: { zh: '', en: 'Higher customer satisfaction' } },
        ],
      },
      B: {
        owner: 'Grace Chen', teamSize: 5, period: '2025/12/01 - 2026/01/23', status: 'in_progress',
        team: [{ role: 'PM', count: 1 }, { role: 'RD', count: 2 }, { role: 'QC', count: 1 }, { role: 'SA', count: 1 }],
        wbs: [
          { phase: 'kickoff', weeks: 1, date: '12/1 - 12/5' },
          { phase: 'analysis', weeks: 1, date: '12/8 - 12/12' },
          { phase: 'design_dev', weeks: 3, date: '12/15 - 1/2' },
          { phase: 'testing', weeks: 1, date: '1/5 - 1/9' },
          { phase: 'uat', weeks: 2, date: '1/12 - 1/23', ongoing: true },
        ],
        cost: { total: 'NT$ 1,420,000', manDays: 36 },
        deliverables: ['workflow_template', 'uat_report'],
      },
      C: {
        architecture: ['user', 'ai_portal', 'n8n_workflow', 'claude_bedrock', 'external_sources'],
        techStack: ['aws_ec2', 'bedrock_claude3', 'n8n_self_hosting', 'restful_api'],
        coreFunctions: ['form_extraction', 'data_matching', 'report_gen'],
      },
    },
  },
  {
    id: 6,
    industry: 'Financial Services',
    icon: '📊',
    title: { zh: '智能投資組合分析平台', en: 'Smart Portfolio Analytics Platform' },
    description: { zh: 'AI 分析市場數據，提供投資組合優化建議。', en: 'AI analyzes market data to provide portfolio optimization recommendations.' },
    serviceCategory: 'data_analytics', useCase: 'data_insight', skills: ['aws'], date: '2025-10-20', creator: 'Ivan Hsu',
    detail: {
      A: {
        industryBackground: { zh: '該客戶為財富管理機構，服務數千名高資產客戶，理財顧問需依市場變化隨時調整投資組合建議，客戶對即時性與客製化的要求日益提高。', en: 'A wealth management firm serving thousands of high-net-worth clients, where advisors must continually adjust portfolio recommendations as markets move, and clients increasingly expect real-time, personalized advice.' },
        challenge: { zh: '市場數據來源分散且更新頻繁，理財顧問難以在有限時間內綜合分析大量資訊並即時評估最佳資產配置，容易錯過調整時機或給出過於保守的建議。', en: 'Market data comes from scattered, fast-updating sources, making it hard for advisors to synthesize large volumes of information in time to assess optimal allocation — often missing the right moment to act or defaulting to overly conservative advice.' },
        solution: { zh: 'AI 模型即時彙整市場數據與客戶風險屬性，自動產生客製化資產配置建議與情境分析，讓理財顧問能更快回應市場變化並提升服務效率。', en: 'AI aggregates market data and client risk profiles in real time, automatically producing personalized allocation recommendations and scenario analysis — letting advisors respond to market moves faster and serve more clients efficiently.' },
        kpis: [
          { icon: '⏱️', value: '3x', label: { zh: '分析效率提升', en: 'Analysis efficiency' } },
          { icon: '🕑', value: '12hr', label: { zh: '每月省人力', en: 'Labor hours saved / mo' } },
          { icon: '💰', value: 'NT$150K', label: { zh: '年節省成本', en: 'Cost saved / yr' } },
          { icon: '✅', value: '客製化建議', label: { zh: '', en: 'Personalized recommendations' } },
        ],
      },
      B: {
        owner: 'Ivan Hsu', teamSize: 5, period: '2026/02/09 - 2026/04/03', status: 'planning',
        team: [{ role: 'PM', count: 1 }, { role: 'RD', count: 2 }, { role: 'SA', count: 1 }, { role: 'QC', count: 1 }],
        wbs: [
          { phase: 'kickoff', weeks: 1, date: '2/9 - 2/13' },
          { phase: 'analysis', weeks: 1, date: '2/16 - 2/20' },
          { phase: 'design_dev', weeks: 4, date: '2/23 - 3/20' },
          { phase: 'testing', weeks: 1, date: '3/23 - 3/27' },
          { phase: 'uat', weeks: 1, date: '3/30 - 4/3', ongoing: true },
        ],
        cost: { total: 'NT$ 1,760,000', manDays: 44 },
        deliverables: ['user_manual', 'uat_report'],
      },
      C: {
        architecture: ['user', 'ai_portal', 'n8n_workflow', 'claude_bedrock', 'external_sources'],
        techStack: ['sagemaker', 'quicksight', 'python', 'aws_rds'],
        coreFunctions: ['data_matching', 'dashboard', 'report_gen'],
      },
    },
  },
  {
    id: 7,
    industry: 'Financial Services',
    icon: '🚨',
    title: { zh: '反詐騙交易監控系統', en: 'Anti-fraud Transaction Monitoring System' },
    description: { zh: '即時監控交易行為，AI 偵測異常即時告警。', en: 'Monitors transactions in real time; AI detects and alerts on anomalies instantly.' },
    serviceCategory: 'ai_genai', useCase: 'fraud_detect', skills: ['aws'], date: '2025-10-18', creator: 'Nina Fang',
    detail: {
      A: {
        industryBackground: { zh: '該客戶為支付服務業者，每日處理數十萬筆交易，服務對象涵蓋電商與實體商家，交易型態多元且持續面臨新興詐騙手法的攻擊。', en: 'A payment service provider processing hundreds of thousands of transactions daily across e-commerce and physical merchants, facing constantly evolving fraud tactics across diverse transaction types.' },
        challenge: { zh: '詐騙交易手法不斷翻新，傳統固定規則難以及時識別新型態異常模式，人工覆核所有警示交易又不符成本效益，容易造成漏判或誤判。', en: "Fraud tactics keep evolving, and static rule sets struggle to catch new anomaly patterns in time; manually reviewing every flagged transaction isn't cost-effective either, leading to missed fraud or false positives." },
        solution: { zh: 'AI 模型即時分析交易行為模式並持續學習新型態詐騙手法，異常交易觸發即時告警並自動評分風險等級，讓風控團隊能優先處理高風險案件。', en: 'AI analyzes transaction behavior patterns in real time and continuously learns emerging fraud tactics, triggering instant alerts with an automatic risk score — so the risk team can prioritize the highest-risk cases first.' },
        kpis: [
          { icon: '⏱️', value: '80%', label: { zh: '偵測速度提升', en: 'Faster detection' } },
          { icon: '🕑', value: '30hr', label: { zh: '每月省人力', en: 'Labor hours saved / mo' } },
          { icon: '💰', value: 'NT$400K', label: { zh: '減少詐騙損失', en: 'Fraud loss avoided / yr' } },
          { icon: '✅', value: '即時告警', label: { zh: '', en: 'Real-time alerting' } },
        ],
      },
      B: {
        owner: 'Nina Fang', teamSize: 6, period: '2026/01/26 - 2026/03/27', status: 'planning',
        team: [{ role: 'PM', count: 1 }, { role: 'RD', count: 3 }, { role: 'SA', count: 1 }, { role: 'QC', count: 1 }],
        wbs: [
          { phase: 'kickoff', weeks: 1, date: '1/26 - 1/30' },
          { phase: 'analysis', weeks: 1, date: '2/2 - 2/6' },
          { phase: 'design_dev', weeks: 4, date: '2/9 - 3/6' },
          { phase: 'testing', weeks: 2, date: '3/9 - 3/20' },
          { phase: 'uat', weeks: 1, date: '3/23 - 3/27', ongoing: true },
        ],
        cost: { total: 'NT$ 2,100,000', manDays: 52 },
        deliverables: ['workflow_template', 'ops_manual', 'uat_report'],
      },
      C: {
        architecture: ['user', 'ai_portal', 'n8n_workflow', 'claude_bedrock', 'external_sources'],
        techStack: ['sagemaker', 'aws_lambda', 'python', 'aws_rds'],
        coreFunctions: ['anomaly_alert', 'risk_scoring', 'notification', 'dashboard'],
      },
    },
  },
  {
    id: 8,
    industry: 'Financial Services',
    icon: '🔐',
    title: { zh: '法遵文件管理平台', en: 'Regulatory Compliance Document Platform' },
    description: { zh: '集中管理法遵文件，AI 協助分類與檢索。', en: 'Centralizes compliance documents; AI assists classification and retrieval.' },
    serviceCategory: 'ai_genai', useCase: 'nlp', skills: ['aws'], date: '2025-10-18', creator: 'Oscar Yang',
    detail: {
      A: {
        industryBackground: { zh: '該客戶為金融機構法遵部門，須管理跨多個業務單位產生的法規遵循文件，隨著法規更新頻繁，文件版本與異動追蹤的複雜度持續上升。', en: "A financial institution's compliance department managing regulatory documents produced across multiple business units, where frequent regulatory updates keep increasing the complexity of version and change tracking." },
        challenge: { zh: '法遵文件分散存放於各部門的共用資料夾與信件附件，人員需要時常跨部門詢問才能找到最新版本，檢索耗時且版本管理混亂，稽核時難以快速提供完整紀錄。', en: 'Compliance documents are scattered across departmental shared folders and email attachments, forcing staff to chase colleagues across teams just to find the latest version — slow to search, messy to version, and hard to produce a complete audit trail quickly.' },
        solution: { zh: '集中式平台結合 NLP 自動分類與標籤文件，並記錄每次異動版本，使用者可依關鍵字快速檢索，稽核時也能一鍵匯出完整異動歷程。', en: 'A centralized platform uses NLP to auto-classify and tag documents and logs every revision, so users can search by keyword instantly and export a complete change history with one click during an audit.' },
        kpis: [
          { icon: '⏱️', value: '65%', label: { zh: '檢索時間縮短', en: 'Faster document retrieval' } },
          { icon: '🕑', value: '16hr', label: { zh: '每月省人力', en: 'Labor hours saved / mo' } },
          { icon: '💰', value: 'NT$140K', label: { zh: '年節省成本', en: 'Cost saved / yr' } },
          { icon: '✅', value: '版本追蹤', label: { zh: '', en: 'Version traceability' } },
        ],
      },
      B: {
        owner: 'Oscar Yang', teamSize: 4, period: '2025/11/24 - 2026/01/09', status: 'in_progress',
        team: [{ role: 'PM', count: 1 }, { role: 'RD', count: 1 }, { role: 'SA', count: 1 }, { role: 'QC', count: 1 }],
        wbs: [
          { phase: 'kickoff', weeks: 1, date: '11/24 - 11/28' },
          { phase: 'analysis', weeks: 1, date: '12/1 - 12/5' },
          { phase: 'design_dev', weeks: 3, date: '12/8 - 12/26' },
          { phase: 'testing', weeks: 1, date: '12/29 - 1/2' },
          { phase: 'uat', weeks: 1, date: '1/5 - 1/9', ongoing: true },
        ],
        cost: { total: 'NT$ 1,120,000', manDays: 28 },
        deliverables: ['user_manual', 'uat_report'],
      },
      C: {
        architecture: ['user', 'ai_portal', 'n8n_workflow', 'claude_bedrock', 'external_sources'],
        techStack: ['aws_s3', 'nlp', 'python', 'restful_api'],
        coreFunctions: ['data_matching', 'dashboard'],
      },
    },
  },
  {
    id: 9,
    industry: 'Healthcare',
    icon: '🩺',
    title: { zh: '智慧病歷摘要生成系統', en: 'Smart Medical Record Summarization' },
    description: { zh: 'AI 自動彙整病歷資訊，生成結構化摘要供醫師快速閱讀。', en: 'AI aggregates medical records into structured summaries for quick physician review.' },
    serviceCategory: 'ai_genai', useCase: 'nlp', skills: ['aws', 'claude'], date: '2025-10-15', creator: 'Dr. Lily Tsai',
    detail: {
      A: {
        industryBackground: { zh: '該客戶為區域醫院，門診量大，各科醫師看診前常需查閱病人過去多次就診紀錄，病歷內容分散在不同科別系統中。', en: "A regional hospital with high outpatient volume, where physicians across departments frequently need to review a patient's prior visit history scattered across different departmental systems before each consultation." },
        challenge: { zh: '病歷內容龐雜且分散於多個系統，醫師看診前需耗費大量時間逐一翻閱過去病史、檢驗報告與用藥紀錄，看診時間因此被壓縮，影響問診品質。', en: 'Medical records are voluminous and scattered across systems; physicians spend significant time paging through past history, lab results, and medication records before each consultation, squeezing actual consultation time and affecting care quality.' },
        solution: { zh: 'AI 自動彙整病人歷次就診資料，生成結構化的重點摘要，讓醫師在看診前幾分鐘內就能掌握病史全貌，把更多時間留給問診與治療決策。', en: "AI automatically compiles a patient's past visit records into a structured, key-point summary, letting physicians grasp the full history within minutes before a consultation and spend more time on diagnosis and treatment decisions." },
        kpis: [
          { icon: '⏱️', value: '40%', label: { zh: '看診準備時間縮短', en: 'Faster consultation prep' } },
          { icon: '🕑', value: '10hr', label: { zh: '每月省人力', en: 'Labor hours saved / mo' } },
          { icon: '💰', value: 'NT$120K', label: { zh: '年節省成本', en: 'Cost saved / yr' } },
          { icon: '✅', value: '看診品質提升', label: { zh: '', en: 'Improved consultation quality' } },
        ],
      },
      B: {
        owner: 'Dr. Lily Tsai', teamSize: 5, period: '2026/01/05 - 2026/02/27', status: 'planning',
        team: [{ role: 'PM', count: 1 }, { role: 'RD', count: 2 }, { role: 'SA', count: 1 }, { role: 'QC', count: 1 }],
        wbs: [
          { phase: 'kickoff', weeks: 1, date: '1/5 - 1/9' },
          { phase: 'analysis', weeks: 1, date: '1/12 - 1/16' },
          { phase: 'design_dev', weeks: 3, date: '1/19 - 2/6' },
          { phase: 'testing', weeks: 1, date: '2/9 - 2/13' },
          { phase: 'uat', weeks: 2, date: '2/16 - 2/27', ongoing: true },
        ],
        cost: { total: 'NT$ 1,340,000', manDays: 34 },
        deliverables: ['user_manual', 'training_session', 'uat_report'],
      },
      C: {
        architecture: ['user', 'ai_portal', 'n8n_workflow', 'claude_bedrock', 'external_sources'],
        techStack: ['bedrock_claude3', 'nlp', 'aws_rds', 'restful_api'],
        coreFunctions: ['data_matching', 'report_gen', 'dashboard'],
      },
    },
  },
  {
    id: 10,
    industry: 'Healthcare',
    icon: '💊',
    title: { zh: '用藥安全風險預警平台', en: 'Medication Safety Risk Alert Platform' },
    description: { zh: 'AI 分析用藥紀錄，即時預警交互作用與過量風險。', en: 'AI analyzes medication records to alert on interaction and overdose risks in real time.' },
    serviceCategory: 'data_analytics', useCase: 'data_insight', skills: ['aws'], date: '2025-10-12', creator: 'Dr. Kevin Ho',
    detail: {
      A: {
        industryBackground: { zh: '該客戶為長期照護機構，服務對象多為高齡與慢性病患者，同時服用多種藥物的比例偏高，用藥安全管理是機構長期關注的核心議題。', en: 'A long-term care provider serving mostly elderly and chronically ill residents with a high rate of polypharmacy, where medication safety management is a long-standing core concern for the facility.' },
        challenge: { zh: '多重用藥的交互作用風險難以由護理人員人工即時掌握，藥物種類與劑量調整頻繁，稍有疏漏就可能引發嚴重的藥物交互作用或過量風險。', en: 'Nursing staff struggle to manually track drug-interaction risk in real time for residents on multiple medications, and frequent dosage adjustments mean even a small oversight can trigger serious interactions or overdose risk.' },
        solution: { zh: 'AI 即時交叉分析每位住民的用藥紀錄與最新處方，自動偵測潛在交互作用與過量風險並主動預警，讓護理人員能在給藥前及時介入處理。', en: 'AI cross-analyzes each resident\'s medication history against the latest prescriptions in real time, automatically detecting potential interactions and overdose risk and proactively alerting staff to intervene before medication is administered.' },
        kpis: [
          { icon: '⏱️', value: '30%', label: { zh: '用藥風險事件下降', en: 'Fewer medication risk events' } },
          { icon: '🕑', value: '8hr', label: { zh: '每月省人力', en: 'Labor hours saved / mo' } },
          { icon: '💰', value: 'NT$90K', label: { zh: '年節省成本', en: 'Cost saved / yr' } },
          { icon: '✅', value: '即時預警', label: { zh: '', en: 'Real-time alerts' } },
        ],
      },
      B: {
        owner: 'Dr. Kevin Ho', teamSize: 4, period: '2026/02/16 - 2026/04/03', status: 'planning',
        team: [{ role: 'PM', count: 1 }, { role: 'RD', count: 1 }, { role: 'SA', count: 1 }, { role: 'QC', count: 1 }],
        wbs: [
          { phase: 'kickoff', weeks: 1, date: '2/16 - 2/20' },
          { phase: 'analysis', weeks: 1, date: '2/23 - 2/27' },
          { phase: 'design_dev', weeks: 4, date: '3/2 - 3/27' },
          { phase: 'testing', weeks: 1, date: '3/30 - 4/3' },
        ],
        cost: { total: 'NT$ 1,080,000', manDays: 27 },
        deliverables: ['ops_manual', 'uat_report'],
      },
      C: {
        architecture: ['user', 'ai_portal', 'n8n_workflow', 'claude_bedrock', 'external_sources'],
        techStack: ['sagemaker', 'aws_rds', 'python'],
        coreFunctions: ['anomaly_alert', 'notification', 'dashboard'],
      },
    },
  },
  {
    id: 11,
    industry: 'Healthcare',
    icon: '🩻',
    title: { zh: '醫療影像輔助判讀系統', en: 'AI-assisted Medical Imaging Review' },
    description: { zh: 'AI 輔助判讀醫療影像，提升初步篩檢效率。', en: 'AI assists in reading medical images to improve initial screening efficiency.' },
    serviceCategory: 'ai_genai', useCase: 'ocr', skills: ['aws'], date: '2025-10-08', creator: 'Dr. Wendy Lo',
    detail: {
      A: {
        industryBackground: { zh: '該客戶為醫學影像中心，每日產出的X光、CT與超音波影像數量龐大，而具資深判讀經驗的放射科醫師人力長期吃緊。', en: 'A medical imaging center generating a high daily volume of X-ray, CT, and ultrasound scans, while experienced radiologists remain in chronically short supply.' },
        challenge: { zh: '影像判讀量遠超過放射科醫師的可負荷產能，初步篩檢每張影像都需要仔細比對過去影像與臨床資訊，耗費大量時間也容易因疲勞影響判讀品質。', en: 'Imaging volume far exceeds radiologist capacity, and initial screening of each scan requires careful comparison against prior images and clinical data — a time-consuming process where fatigue can also affect reading quality.' },
        solution: { zh: 'AI 輔助標記影像中的可疑異常區域並排序疑似風險等級，讓醫師優先檢視高風險影像，加速初步篩檢流程並降低漏診風險，最終診斷仍由醫師確認。', en: 'AI highlights suspicious regions in each scan and ranks them by likely risk level, letting radiologists review the highest-risk images first — speeding up initial screening and reducing the chance of missed findings, while the physician still makes the final diagnosis.' },
        kpis: [
          { icon: '⏱️', value: '35%', label: { zh: '篩檢時間縮短', en: 'Faster screening' } },
          { icon: '🕑', value: '14hr', label: { zh: '每月省人力', en: 'Labor hours saved / mo' } },
          { icon: '💰', value: 'NT$160K', label: { zh: '年節省成本', en: 'Cost saved / yr' } },
          { icon: '✅', value: '輔助判讀', label: { zh: '', en: 'Assisted reading, not replacing physicians' } },
        ],
      },
      B: {
        owner: 'Dr. Wendy Lo', teamSize: 5, period: '2026/03/02 - 2026/05/01', status: 'planning',
        team: [{ role: 'PM', count: 1 }, { role: 'RD', count: 2 }, { role: 'SA', count: 1 }, { role: 'QC', count: 1 }],
        wbs: [
          { phase: 'kickoff', weeks: 1, date: '3/2 - 3/6' },
          { phase: 'analysis', weeks: 1, date: '3/9 - 3/13' },
          { phase: 'design_dev', weeks: 4, date: '3/16 - 4/10' },
          { phase: 'testing', weeks: 2, date: '4/13 - 4/24' },
          { phase: 'uat', weeks: 1, date: '4/27 - 5/1', ongoing: true },
        ],
        cost: { total: 'NT$ 1,900,000', manDays: 48 },
        deliverables: ['training_session', 'uat_report'],
      },
      C: {
        architecture: ['user', 'ai_portal', 'n8n_workflow', 'claude_bedrock', 'external_sources'],
        techStack: ['sagemaker', 'aws_s3', 'python'],
        coreFunctions: ['data_matching', 'anomaly_alert', 'report_gen'],
      },
    },
  },
  {
    id: 12,
    industry: 'Retail',
    icon: '🛒',
    title: { zh: '智慧零售需求預測平台', en: 'Smart Retail Demand Forecasting Platform' },
    description: { zh: 'AI 預測商品需求，優化庫存與補貨決策。', en: 'AI forecasts product demand to optimize inventory and replenishment decisions.' },
    serviceCategory: 'data_analytics', useCase: 'demand_forecast', skills: ['aws'], date: '2025-10-05', creator: 'Sam Chiu',
    detail: {
      A: {
        industryBackground: { zh: '該客戶為連鎖零售品牌，門市遍布多個區域，商品品類眾多且季節性波動明顯，庫存決策長期仰賴各店店長的經驗判斷。', en: "A retail chain with stores across multiple regions carrying a wide, seasonally volatile product range, where inventory decisions have long relied on individual store managers' experience." },
        challenge: { zh: '庫存預測缺乏數據支持，各門市對同一商品的備貨判斷不一致，旺季常發生缺貨錯失銷售機會，淡季又容易囤積過剩庫存增加資金壓力。', en: 'Inventory forecasting lacks data support, so stocking decisions for the same product vary inconsistently store to store — leading to lost sales from stockouts during peak season and excess inventory tying up cash during slow periods.' },
        solution: { zh: 'AI 模型整合歷史銷售、季節趨勢與促銷活動等外部因子，為每個門市與品類產生精準的需求預測，並自動產生補貨建議，統一決策標準。', en: 'AI models combine historical sales, seasonal trends, and external factors like promotions to generate accurate demand forecasts per store and category, automatically producing replenishment recommendations that standardize decision-making.' },
        kpis: [
          { icon: '⏱️', value: '25%', label: { zh: '缺貨率下降', en: 'Lower stockout rate' } },
          { icon: '🕑', value: '18%', label: { zh: '庫存成本降低', en: 'Lower inventory cost' } },
          { icon: '💰', value: 'NT$500K', label: { zh: '年節省成本', en: 'Cost saved / yr' } },
          { icon: '✅', value: '補貨自動化', label: { zh: '', en: 'Automated replenishment' } },
        ],
      },
      B: {
        owner: 'Sam Chiu', teamSize: 5, period: '2026/01/12 - 2026/03/13', status: 'planning',
        team: [{ role: 'PM', count: 1 }, { role: 'RD', count: 2 }, { role: 'SA', count: 1 }, { role: 'QC', count: 1 }],
        wbs: [
          { phase: 'kickoff', weeks: 1, date: '1/12 - 1/16' },
          { phase: 'analysis', weeks: 1, date: '1/19 - 1/23' },
          { phase: 'design_dev', weeks: 4, date: '1/26 - 2/20' },
          { phase: 'testing', weeks: 2, date: '2/23 - 3/6' },
          { phase: 'uat', weeks: 1, date: '3/9 - 3/13', ongoing: true },
        ],
        cost: { total: 'NT$ 1,700,000', manDays: 43 },
        deliverables: ['ops_manual', 'uat_report'],
      },
      C: {
        architecture: ['user', 'ai_portal', 'n8n_workflow', 'claude_bedrock', 'external_sources'],
        techStack: ['sagemaker', 'quicksight', 'aws_rds', 'python'],
        coreFunctions: ['data_matching', 'dashboard', 'notification'],
      },
    },
  },
  {
    id: 13,
    industry: 'Retail',
    icon: '💬',
    title: { zh: '客服對話機器人升級專案', en: 'Customer Service Chatbot Upgrade Project' },
    description: { zh: '導入 GenAI 對話引擎，提升客服自動化解決率。', en: 'Introduces a GenAI conversation engine to improve automated resolution rates.' },
    serviceCategory: 'ai_genai', useCase: 'conversation', skills: ['aws', 'claude'], date: '2025-09-28', creator: 'Ella Fan',
    detail: {
      A: {
        industryBackground: { zh: '該客戶為電商零售品牌，客服團隊每日需處理大量訂單查詢、退換貨與商品諮詢，尖峰檔期（如促銷檔期）諮詢量會暴增數倍。', en: 'An e-commerce retail brand whose customer service team handles a high volume of order inquiries, returns, and product questions daily, with inquiry volume spiking several-fold during major promotional periods.' },
        challenge: { zh: '既有的規則式客服機器人只能處理固定問答，遇到稍微變化的問法就無法理解，大量問題最終仍轉接人工客服，客戶滿意度與客服團隊負擔都受到影響。', en: "The existing rule-based chatbot can only handle fixed question-answer pairs and fails on slightly rephrased questions, so most inquiries still escalate to human agents — hurting both customer satisfaction and team workload." },
        solution: { zh: '導入 GenAI 對話引擎，理解更自然的提問方式並串接訂單系統即時查詢，大幅提升自動化解決率，僅將複雜或情緒性案件轉接真人客服。', en: 'A GenAI conversation engine understands more natural phrasing and connects directly to the order system for real-time lookups, greatly improving automated resolution and escalating only complex or sensitive cases to human agents.' },
        kpis: [
          { icon: '⏱️', value: '2x', label: { zh: '自動化解決率提升', en: 'Auto-resolution rate' } },
          { icon: '🕑', value: '20hr', label: { zh: '每月省人力', en: 'Labor hours saved / mo' } },
          { icon: '💰', value: 'NT$220K', label: { zh: '年節省成本', en: 'Cost saved / yr' } },
          { icon: '✅', value: '滿意度提升', label: { zh: '', en: 'Higher CSAT' } },
        ],
      },
      B: {
        owner: 'Ella Fan', teamSize: 5, period: '2025/12/08 - 2026/02/06', status: 'in_progress',
        team: [{ role: 'PM', count: 1 }, { role: 'RD', count: 2 }, { role: 'SA', count: 1 }, { role: 'UIUX', count: 1 }],
        wbs: [
          { phase: 'kickoff', weeks: 1, date: '12/8 - 12/12' },
          { phase: 'analysis', weeks: 1, date: '12/15 - 12/19' },
          { phase: 'design_dev', weeks: 4, date: '12/22 - 1/16' },
          { phase: 'testing', weeks: 2, date: '1/19 - 1/30' },
          { phase: 'uat', weeks: 1, date: '2/2 - 2/6', ongoing: true },
        ],
        cost: { total: 'NT$ 1,580,000', manDays: 40 },
        deliverables: ['user_manual', 'training_session', 'uat_report'],
      },
      C: {
        architecture: ['user', 'ai_portal', 'n8n_workflow', 'claude_bedrock', 'external_sources'],
        techStack: ['bedrock_claude3', 'nlp', 'aws_lambda', 'restful_api'],
        coreFunctions: ['dashboard', 'notification'],
      },
    },
  },
  {
    id: 14,
    industry: 'Manufacturing',
    icon: '⚙️',
    title: { zh: '產線設備異常偵測系統', en: 'Production Line Equipment Anomaly Detection' },
    description: { zh: 'AI 即時監測設備數據，提前預警異常與故障。', en: 'AI monitors equipment data in real time to give early warnings of anomalies and failures.' },
    serviceCategory: 'ai_genai', useCase: 'equipment_monitor', skills: ['aws'], date: '2025-09-20', creator: 'Marcus Lee',
    detail: {
      A: {
        industryBackground: { zh: '該客戶為連續生產型製造廠，產線一旦停機將直接影響整條供應鏈的出貨排程，設備妥善率是管理層長期關注的關鍵指標。', en: 'A continuous-production manufacturer where any line stoppage directly disrupts downstream shipping schedules, making equipment uptime a key metric that management closely tracks.' },
        challenge: { zh: '設備異常往往在故障發生後才被人工發現，此時產線已經停機，不僅造成當班產出損失，緊急排修也常需要加班處理，增加額外成本。', en: 'Equipment anomalies are typically discovered manually only after a breakdown, by which point the line has already stopped — causing lost output for that shift and often requiring costly overtime for emergency repairs.' },
        solution: { zh: 'AI 即時分析設備感測器數據，在異常初期就偵測出偏離正常範圍的訊號並主動預警，讓維護團隊能安排計畫性保養，避免非預期停機。', en: 'AI analyzes equipment sensor data in real time, detecting early-stage deviations from normal patterns and proactively alerting the maintenance team — enabling planned upkeep instead of unplanned downtime.' },
        kpis: [
          { icon: '⏱️', value: '40%', label: { zh: '停機時間減少', en: 'Less downtime' } },
          { icon: '🕑', value: '35hr', label: { zh: '每月省人力', en: 'Labor hours saved / mo' } },
          { icon: '💰', value: 'NT$600K', label: { zh: '年節省成本', en: 'Cost saved / yr' } },
          { icon: '✅', value: '預防性維護', label: { zh: '', en: 'Predictive maintenance' } },
        ],
      },
      B: {
        owner: 'Marcus Lee', teamSize: 6, period: '2026/02/23 - 2026/05/01', status: 'planning',
        team: [{ role: 'PM', count: 1 }, { role: 'RD', count: 3 }, { role: 'SA', count: 1 }, { role: 'QC', count: 1 }],
        wbs: [
          { phase: 'kickoff', weeks: 1, date: '2/23 - 2/27' },
          { phase: 'analysis', weeks: 1, date: '3/2 - 3/6' },
          { phase: 'design_dev', weeks: 5, date: '3/9 - 4/10' },
          { phase: 'testing', weeks: 2, date: '4/13 - 4/24' },
          { phase: 'uat', weeks: 1, date: '4/27 - 5/1', ongoing: true },
        ],
        cost: { total: 'NT$ 2,200,000', manDays: 55 },
        deliverables: ['ops_manual', 'source_repo', 'uat_report'],
      },
      C: {
        architecture: ['user', 'ai_portal', 'n8n_workflow', 'claude_bedrock', 'external_sources'],
        techStack: ['sagemaker', 'aws_lambda', 'python', 'aws_rds'],
        coreFunctions: ['anomaly_alert', 'dashboard', 'notification'],
      },
    },
  },
  {
    id: 15,
    industry: 'Manufacturing',
    icon: '🧾',
    title: { zh: '供應鏈品質稽核平台', en: 'Supply Chain Quality Audit Platform' },
    description: { zh: '自動彙整供應商品質文件，AI 協助偵測異常趨勢。', en: 'Aggregates supplier quality documents; AI helps detect anomalous trends.' },
    serviceCategory: 'automation', useCase: 'fraud_detect', skills: ['aws'], date: '2025-09-15', creator: 'Tina Chou',
    detail: {
      A: {
        industryBackground: { zh: '該客戶為製造業採購部門，長期與數十家供應商合作，各供應商提交的品質檢驗報告格式不一，稽核作業量隨供應商數量成長而持續增加。', en: 'A manufacturing procurement department working with dozens of suppliers, each submitting quality inspection reports in inconsistent formats, with audit workload growing alongside the supplier base.' },
        challenge: { zh: '供應商品質文件分散存放且格式不統一，採購人員需人工彙整比對才能判斷品質趨勢，往往要等到問題累積到一定程度才被發現，稽核也難以追溯完整歷程。', en: "Supplier quality documents are scattered and inconsistently formatted; buyers must manually compile and compare them to spot quality trends, so issues often surface only after they've accumulated, and audits struggle to trace a complete history." },
        solution: { zh: '自動彙整各供應商的品質文件並統一格式，AI 持續分析歷史數據偵測異常趨勢，及早示警品質下滑的供應商，也能一鍵匯出完整稽核紀錄。', en: 'The platform automatically aggregates and standardizes supplier quality documents, with AI continuously analyzing historical data to detect anomalous trends and flag declining suppliers early — while also exporting a complete audit record in one click.' },
        kpis: [
          { icon: '⏱️', value: '50%', label: { zh: '稽核時間縮短', en: 'Faster audits' } },
          { icon: '🕑', value: '24hr', label: { zh: '每月省人力', en: 'Labor hours saved / mo' } },
          { icon: '💰', value: 'NT$280K', label: { zh: '年節省成本', en: 'Cost saved / yr' } },
          { icon: '✅', value: '趨勢預警', label: { zh: '', en: 'Trend-based early warning' } },
        ],
      },
      B: {
        owner: 'Tina Chou', teamSize: 4, period: '2025/11/17 - 2026/01/16', status: 'in_progress',
        team: [{ role: 'PM', count: 1 }, { role: 'RD', count: 1 }, { role: 'SA', count: 1 }, { role: 'QC', count: 1 }],
        wbs: [
          { phase: 'kickoff', weeks: 1, date: '11/17 - 11/21' },
          { phase: 'analysis', weeks: 1, date: '11/24 - 11/28' },
          { phase: 'design_dev', weeks: 4, date: '12/1 - 12/26' },
          { phase: 'testing', weeks: 2, date: '12/29 - 1/9' },
          { phase: 'uat', weeks: 1, date: '1/12 - 1/16', ongoing: true },
        ],
        cost: { total: 'NT$ 1,260,000', manDays: 32 },
        deliverables: ['workflow_template', 'uat_report'],
      },
      C: {
        architecture: ['user', 'ai_portal', 'n8n_workflow', 'claude_bedrock', 'external_sources'],
        techStack: ['n8n_self_hosting', 'aws_s3', 'python'],
        coreFunctions: ['data_matching', 'anomaly_alert', 'dashboard'],
      },
    },
  },
  {
    id: 16,
    industry: 'Logistics',
    icon: '🚚',
    title: { zh: '物流路線優化與追蹤系統', en: 'Logistics Route Optimization & Tracking' },
    description: { zh: 'AI 動態優化配送路線，即時追蹤車輛與貨況。', en: 'AI dynamically optimizes delivery routes and tracks vehicles and cargo in real time.' },
    serviceCategory: 'data_analytics', useCase: 'route_optimize', skills: ['aws'], date: '2025-09-10', creator: 'Ray Peng',
    detail: {
      A: {
        industryBackground: { zh: '該客戶為物流配送業者，每日派車服務數百個收送貨點，服務範圍涵蓋市區與郊區，路況與客戶收貨時段限制都相當多元。', en: 'A logistics delivery operator dispatching vehicles to hundreds of pickup and drop-off points daily across both urban and suburban areas, with highly variable traffic conditions and customer delivery-window constraints.' },
        challenge: { zh: '配送路線多依賴調度人員的經驗排定，難以同時考量即時路況、車輛容量與收貨時段限制，尖峰時段常因路況延誤打亂原訂排程，客戶也難以掌握確切到貨時間。', en: "Delivery routes are largely planned on dispatcher experience alone, making it hard to account for real-time traffic, vehicle capacity, and delivery-window constraints simultaneously — peak-hour delays routinely disrupt schedules, and customers can't get a reliable ETA." },
        solution: { zh: 'AI 動態計算考量即時路況、車輛容量與收貨時段限制的最佳配送路線，並提供即時追蹤與到貨時間預估，讓派車更有效率、客戶體驗也更透明。', en: 'AI dynamically computes optimal routes that account for real-time traffic, vehicle capacity, and delivery windows, while providing live tracking and ETA estimates — making dispatch more efficient and the customer experience more transparent.' },
        kpis: [
          { icon: '⏱️', value: '20%', label: { zh: '配送時間縮短', en: 'Faster delivery' } },
          { icon: '🕑', value: '15%', label: { zh: '油耗成本降低', en: 'Lower fuel cost' } },
          { icon: '💰', value: 'NT$350K', label: { zh: '年節省成本', en: 'Cost saved / yr' } },
          { icon: '✅', value: '即時追蹤', label: { zh: '', en: 'Real-time tracking' } },
        ],
      },
      B: {
        owner: 'Ray Peng', teamSize: 5, period: '2026/03/09 - 2026/05/08', status: 'planning',
        team: [{ role: 'PM', count: 1 }, { role: 'RD', count: 2 }, { role: 'SA', count: 1 }, { role: 'QC', count: 1 }],
        wbs: [
          { phase: 'kickoff', weeks: 1, date: '3/9 - 3/13' },
          { phase: 'analysis', weeks: 1, date: '3/16 - 3/20' },
          { phase: 'design_dev', weeks: 4, date: '3/23 - 4/17' },
          { phase: 'testing', weeks: 2, date: '4/20 - 5/1' },
          { phase: 'uat', weeks: 1, date: '5/4 - 5/8', ongoing: true },
        ],
        cost: { total: 'NT$ 1,640,000', manDays: 41 },
        deliverables: ['ops_manual', 'uat_report'],
      },
      C: {
        architecture: ['user', 'ai_portal', 'n8n_workflow', 'claude_bedrock', 'external_sources'],
        techStack: ['aws_lambda', 'quicksight', 'python', 'restful_api'],
        coreFunctions: ['dashboard', 'notification'],
      },
    },
  },
];
